#!/bin/sh

python3 ~/Documents/blog/bin/generate_anki.py ~/Documents/blog/_posts/ ~/Documents/blog/data/Reading.apkg
python3 ~/Documents/blog/bin/generate_jet_anki.py ~/Documents/blog/_posts/jet/ ~/Documents/blog/data/Jet.apkg
python3 ~/Documents/blog/bin/crypto.py >> ~/Documents/blog/data/logs/crypto.csv
python3 ~/Documents/blog/bin/colophon.py 
python3 ~/Documents/blog/bin/extract_run_log.py
python3 ~/Documents/blog/bin/extract_shortcut_health_logs.py
python3 ~/Documents/blog/bin/extract_finance_logs.py
python3 ~/Documents/blog/bin/scrape_rescuetime.py
python3 ~/Documents/blog/bin/log_anki_progress.py
python3 ~/Documents/blog/bin/log_network_status.py 
python3 ~/Documents/blog/bin/log_email_inbox.py
/opt/homebrew/bin/bb ~/Documents/blog/bin/thesis_progress.bb
git add ~/Documents/blog/data/logs/crypto.csv ~/Documents/blog/data/Reading.apkg ~/Documents/blog/data/Jet.apkg ~/Documents/blog/data/logs/ ~/Documents/blog/data/blot/ ~/Documents/blog/_data/
