#!/bin/sh

python3 ~/Documents/blog/crypto.py >> ~/Documents/blog/data/logs/crypto.csv
toggl ls --fields 'id,workspace,description,project,task,billable,start,stop,duration,tags' >> ~/Documents/blog/data/logs/toggl.log
python3 ~/Documents/blog/generate_anki.py ~/Documents/blog/_posts/ ~/Documents/blog/Reading.apkg
todoist --csv completed-list --filter 'today' >> ~/Documents/blog/data/logs/completed_tasks.csv
git add ~/Documents/blog/data/logs/crypto.csv ~/Documents/blog/Reading.apkg ~/Documents/blog/data/logs/completed_tasks.csv ~/Documents/blog/data/logs/toggl
