#!/bin/sh

# check whether there are any changes in the chapters folder
# if there are, then run the scripts to update the progress
# and the summary; otherwise, skip the scripts

# exclude "_reports/chapters" folder
if git diff --cached --name-only | grep "chapters" | grep -v "_reports/chapters"; then
    echo "Updating progress and summary..."
else
    echo "No changes in chapters folder. Skipping progress and summary update..."
    exit 0
fi

# generate an updated progress / 'day log'
/opt/homebrew/bin/bb ~/Documents/thesis/bin/log_thesis_progress.bb
cp ~/Documents/blog/_data/phd/progress.yml ~/Documents/thesis/_reports/progress/day_log.yml

# generate an updated forecast based on progress
/opt/homebrew/bin/bb ~/Documents/thesis/bin/forecast_thesis_progress.bb
cp ~/Documents/blog/_data/phd/forecast.yml ~/Documents/thesis/_reports/progress/day_forecast.yml

# generate updated summaries and reports
/opt/homebrew/bin/python3 ~/Documents/thesis/bin/log.py ~/Documents/thesis/chapters ~/Documents/thesis/_reports/progress/log.json
/opt/homebrew/bin/python3 ~/Documents/thesis/bin/summary.py
/opt/homebrew/bin/python3 ~/Documents/thesis/bin/report.py ~/Documents/thesis/chapters ~/Documents/thesis/_reports/chapters

git add ~/Documents/thesis/_reports