#!/bin/sh

# Check whether there are any changes in the chapters folder.
# If there are, then run the scripts to update the progress and the summary;
# otherwise, skip the scripts. Exclude "_reports/chapters" folder from the check.
if git diff --cached --name-only | grep "chapters" | grep -v "_reports/chapters"; then
    echo "Updating progress and summary..."
else
    echo "No changes in chapters folder. Skipping progress and summary update..."
    exit 0
fi

# generate an updated progress / 'day log'
/opt/homebrew/bin/bb ~/Documents/thesis/bin/log_thesis_progress.bb
cp ~/Documents/blog/_data/phd/progress.yml ~/Documents/thesis/_reports/progress/day_log.yml

# generate an updated forecast based on progress
/opt/homebrew/bin/bb ~/Documents/thesis/bin/forecast_thesis_progress.bb
cp ~/Documents/blog/_data/phd/forecast.yml ~/Documents/thesis/_reports/progress/day_forecast.yml
