# =============================================================================
# Espanso Base Matches - gcuth dotfiles
# =============================================================================
# Core snippets available in all applications.
#
# Trigger conventions:
#   - Double letter prefix (ddate, ttime) for date/time
#   - Double letter prefix (nname, mmail) for personal info
#
# For documentation: https://espanso.org/docs/
# =============================================================================

matches:
  # ---------------------------------------------------------------------------
  # Date & Time
  # ---------------------------------------------------------------------------

  # ISO date: 2024-01-15
  - trigger: "ddate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Time: 14:30:45
  - trigger: "ttime"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M:%S"

  # Full timestamp for logging: 2024-01-15 14:30:45 (+1100) -
  - trigger: "nnow"
    replace: "{{mydate}} {{mytime}} ({{myutcoffset}}) - "
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
      - name: mytime
        type: date
        params:
          format: "%H:%M:%S"
      - name: myutcoffset
        type: date
        params:
          format: "%z"

  # ---------------------------------------------------------------------------
  # Personal Information
  # ---------------------------------------------------------------------------

  - trigger: "nname"
    replace: "Galen Cuthbertson"

  - trigger: "mmail"
    replace: "g@galen.me"
