#!/usr/bin/env sh
# runs an encrypted backup of the directories listed

if (( $# != 0 )); then
    for BASEFOLDER in "$@"; do
        if [ -d $BASEFOLDER ] && [ $(ls $BASEFOLDER | wc -l) -gt 0 ]; then
            now=$(date +%Y-%m-%d-%H-%M-%S)
            echo "Backing up '$BASEFOLDER' ... "
            tar -czvf $(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz $BASEFOLDER
            gpg -c $(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz
            rm ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz
            rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg cloudstor:/backups/ --progress
            rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg gdrive:/backups/ --progress
            # rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg dropbox:/backups/ --progress
            # rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg aws:/backups/ --progress
            if $(lsblk | grep /media | grep -oP "sd[a-z]" | awk '{print "/dev/"$1}' | sort | uniq | wc -l); then
                for EXTMEDIA in `ls /media/$(whoami)`; do
                    cp ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg /media/$(whoami)/$EXTMEDIA
                done
            fi
            rm ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg
        fi
    done
else
    cd ~
    for BASEFOLDER in Documents Code Zotero Videos Pictures Music Recordings Readings Desktop; do
        if [ -d $BASEFOLDER ] && [ $(ls $BASEFOLDER | wc -l) -gt 0 ]; then
            now=$(date +%Y-%m-%d-%H-%M-%S)
            echo "Backing up '$BASEFOLDER' ... "
            tar -czvf $(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz $BASEFOLDER
            gpg -c $(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz
            rm ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz
            rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg cloudstor:/backups/ --progress
            rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg gdrive:/backups/ --progress
            # rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg dropbox:/backups/ --progress
            # rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg aws:/backups/ --progress
            if $(lsblk | grep /media | grep -oP "sd[a-z]" | awk '{print "/dev/"$1}' | sort | uniq | wc -l); then
                for EXTMEDIA in `ls /media/$(whoami)`; do
                    cp ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg /media/$(whoami)/$EXTMEDIA
                done
            fi
            rm ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg
        fi
    done
fi

# to extract, run: gpg -d (file)

