#!/usr/bin/env sh
# runs an encrypted backup of the directories listed
cd ~

now=$(date +%Y-%m-%d-%H-%M-%S)

tar -zcf - Documents Music Pictures Videos Code Zotero | openssl aes-256-cbc -salt -out $(hostname)-$(whoami)-$now.tar.gz.aes

rclone copy ./$(hostname)-$(whoami)-$now.tar.gz.aes cloudstor:/
rclone copy ./$(hostname)-$(whoami)-$now.tar.gz.aes gdrive:/

rm ./$(hostname)-$(whoami)-$now.tar.gz.aes

# to extract, run: openssl aes-256-cbc -d -salt -in backup.tar.gz.aes | tar -xz -f -

