#!/usr/bin/env bash
# runs an encrypted backup of the directories listed

if (( $# != 0 )); then
    for BASEFOLDER in "$@"; do
        if [ -d $BASEFOLDER ] && [ $(ls $BASEFOLDER | wc -l) -gt 0 ]; then
            now=$(date +%Y-%m-%d-%H-%M-%S)
            echo "Backing up '$BASEFOLDER' ... "
            tar -czvf $(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz $BASEFOLDER
            gpg -c $(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz
            rm ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz
            rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg cloudstor:/backups/ --progress
            rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg gdrive:/backups/ --progress
            rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg dropbox:/backups/ --progress
            rm ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg
        fi
    done
else
    cd ~
    for BASEFOLDER in Documents Code Zotero Videos Pictures Music; do
        if [ -d $BASEFOLDER ] && [ $(ls $BASEFOLDER | wc -l) -gt 0 ]; then
            now=$(date +%Y-%m-%d-%H-%M-%S)
            echo "Backing up '$BASEFOLDER' ... "
            tar -czvf $(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz $BASEFOLDER
            gpg -c $(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz
            rm ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz
            rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg cloudstor:/backups/ --progress
            rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg gdrive:/backups/ --progress
            rclone copy ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg dropbox:/backups/ --progress
            rm ./$(hostname)-$(whoami)-$BASEFOLDER-$now.tar.gz.gpg
        fi
    done
fi

# to extract, run: gpg -d (file)

