#!/usr/bin/env sh
#
# A script to update a beeminder thesis goal with current word count total.
# Useful as part of a post-commit hook, with a beeminder 'odometer' goal.

AUTHTOKEN=$(cat ~/.dotfiles/secrets/beeminder/beeminder_auth_token)
USERNAME="galenhimself"
RAW_TOTAL=$(find ~/Documents/thesis/chapters/. -type f -name "*md" -print0 | wc -w --files0-from=- | xargs | awk '{print $(NF-1)}')
BLOCKQUOTE_TOTAL=$(grep -r "^> " ~/Documents/thesis/chapters | wc -w)
COMMENTS_TOTAL=$(grep -r "<\!--" ~/Documents/thesis/chapters | wc -w)
TK_TOTAL=$(rgrep "tk" ~/Documents/thesis/chapters | grep -Ev ".git" | sed 's/ /\n/g' | grep "tk" | wc -l)
CURRENT_TOTAL=$(expr $RAW_TOTAL - $BLOCKQUOTE_TOTAL - $COMMENTS_TOTAL)
# CURRENT_TOTAL=$(expr $RAW_TOTAL - $BLOCKQUOTE_TOTAL - $COMMENTS_TOTAL - $TK_TOTAL)

# Get current goal total from beeminder
RAW_BEEMINDER_INFO=$(curl -s "https://www.beeminder.com/api/v1/users/${USERNAME}/goals/thesis.json?auth_token=${AUTHTOKEN}")
CURRENT_BEE_VALUE=$(echo "$RAW_BEEMINDER_INFO" | python3 -m json.tool | grep -e '.*"curval":.*$' | sed 's/^.*: \([0-9]\+\)/\1/g' | sed 's/\..*//g' | sed "s/[^0-9]//g")

# If current total on local machine doesn't match what's on beeminder, update the beeminder value:
if [ "$CURRENT_TOTAL" -ne "$CURRENT_BEE_VALUE" ]; then
    curl -d "auth_token=${AUTHTOKEN}" -d "value=${CURRENT_TOTAL}" "https://www.beeminder.com/api/v1/users/USERNAME/goals/thesis/datapoints.json"
fi

# Append to a local log just in case
echo $(echo -n $(date +%s); echo -n ", "; echo -n "$CURRENT_TOTAL") >> ~/.dotfiles/secrets/logs/thesis_chapter_words.log
