#!/usr/bin/env sh
#
# A script to update a beeminder 'highlights' goal with the current number of published highlights (from readings/sources).
# Useful as part of a post-commit hook, with a beeminder 'odometer' goal.

AUTHTOKEN=$(cat ~/.dotfiles/secrets/beeminder/auth_token)
USERNAME="galenhimself"
CURRENT_TOTAL=$(grep -R "categories: \['quote'\]" ~/Documents/blog | wc -l)
echo $CURRENT_TOTAL

# Get current goal total from beeminder
RAW_BEEMINDER_INFO=$(curl -s "https://www.beeminder.com/api/v1/users/${USERNAME}/goals/highlight.json?auth_token=${AUTHTOKEN}")
CURRENT_BEE_VALUE=$(echo "$RAW_BEEMINDER_INFO" | python3 -m json.tool | grep -e '.*"curval":.*$' | sed 's/^.*: \([0-9]\+\)/\1/g' | sed 's/\..*//g' | sed "s/[^0-9]//g")

# If current total on local machine doesn't match what's on beeminder, update the beeminder value:
if [ "$CURRENT_TOTAL" -ne "$CURRENT_BEE_VALUE" ]; then
    curl -d "auth_token=${AUTHTOKEN}" -d "value=${CURRENT_TOTAL}" "https://www.beeminder.com/api/v1/users/USERNAME/goals/highlight/datapoints.json"
fi

# Append to a local log just in case
echo $(echo -n $(date +%s); echo -n ", "; echo -n "$CURRENT_TOTAL") >> ~/.dotfiles/secrets/logs/highlight_total.log
