#!/bin/bash
# 
# Purpose: Log screen locks / unlocks (and handle toggl when you do).
# 
# Usage:   nohup ./locklog &

dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" | \
( while true
    do read X
    if echo $X | grep "boolean true" &> /dev/null; then
        echo "$(date), locked" >> $HOME/.dotfiles/secrets/logs/screenlocks.log
        /usr/local/bin/toggl stop
    elif echo $X | grep "boolean false" &> /dev/null; then
        echo "$(date), unlocked" >> $HOME/.dotfiles/secrets/logs/screenlocks.log
    fi
    done )
