#!/bin/bash

# Make it Usable
gsettings set org.gnome.settings-daemon.plugins.media-keys terminal '<Shift><Alt>t'
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-from 20.0
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-to 5.0
gsettings set org.gnome.desktop.session idle-delay 600
gsettings set org.gnome.desktop.screensaver lock-enabled true
gsettings set org.gnome.desktop.screensaver lock-delay 60
gsettings set org.gnome.desktop.screensaver show-notifications false
gsettings set org.gnome.shell.overrides dynamic-workspaces true
gsettings set org.gnome.shell.overrides workspaces-only-on-primary false
gsettings set org.gnome.mutter dynamic-workspaces true
gsettings set org.gnome.mutter workspaces-only-on-primary false
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:swapescape']"
gsettings set org.gnome.desktop.input-sources mru-sources "[('xkb', 'us+dvorak'), ('xkb', 'au')]"
gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us+dvorak'), ('xkb', 'au')]"

# Make it Pretty
gsettings set org.gnome.nautilus.preferences show-hidden-files false
gsettings set org.gnome.shell favorite-apps "[]"
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface icon-theme 'ubuntu-mono-dark'
gsettings set org.gnome.desktop.wm.preferences theme 'Adwaita-dark'
gsettings set org.gnome.desktop.background show-desktop-icons false
gsettings set org.gnome.nautilus.desktop trash-icon-visible false
gsettings set org.gnome.nautilus.desktop home-icon-visible false
gsettings set org.gnome.desktop.background picture-options 'spanned'
gsettings set org.gnome.desktop.interface clock-show-seconds 'false'
gsettings set org.gnome.desktop.interface clock-show-weekday 'false'
gsettings set org.gnome.desktop.interface clock-show-date 'false'

# Deal with the other annoying bits
gsettings set org.gnome.desktop.sound event-sounds 'false'
gsettings set org.gnome.desktop.interface enable-animations 'false'

# Kill active notifications
gsettings set org.gnome.desktop.notifications show-in-lock-screen 'false'
gsettings set org.gnome.desktop.notifications show-banners 'false'

